import type { Metadata } from "next";
import "./globals.css";
import { AppNavBar } from "@/components/navigation/app-navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col dark">
            <header className="h-min">
                <AppNavBar />
            </header>
            <main className="flex relative flex-col h-full">
                <SidebarProvider>
                    <AppSidebar className="flex-shrink-0"/>
                    <article className="flex-grow flex flex-col">
                        <SidebarTrigger />
                        <div className="flex-grow p-2">
                           { children }
                        </div>
                        <footer className="bg-sidebar flex justify-end p-3">
                        </footer>
                    </article>
                </SidebarProvider>
            </main>
            <Toaster/>
        </body>
    </html>
  );
}
